### ISSUE TITLE
Setting Problem, ATS 100=121 not working with new FW version

### ISSUE THREAD

**Issue by JoLo33** [LairdCP/Lyra_Firmware#7] opened 2023-04-19 13:47 UTC
Hey, 

with the older FW ([LYRA-P_AT_Interface_480-00182-R126.3.1.173_UART.gbl) Version ATS 100 was set to 121 and everything was working. After I updated the module to [LYRA-P_AT_Interface_480-00182-R126.3.1.387_UART.gbl suddenly the module was not showing up in any BT Scanning App.

I figured out that the setting ATS 100 is the problem. After I change the setting from ATS 100=121 to ATS 100=9 (default) (enable 1M PHY and not 2M PHY) the module can be found again. If I use the 121 setting the module can't be found. 

Is it a normal behavior? What I'm doing wrong? 

Best Jonas

**Comment by FlorianBaumgartl-Ezurio** [comment] 2023-04-26 13:08
Hi Jonas − I'm curious about which smartphone (vendor, model, OS version) and app you are using for BLE device scanning and discovery. Also, do you have the hardware to e.g. give it a try with another Lyra module or EVK to check if they can see each other? Thanks, Florian.

**Comment by JoLo33** [comment] 2023-04-26 13:19
Hey, 

I use a Huawei BLA-L29 with EMUI-Version 12.0.0 (Android 11) 
Apps: EFR Connect and nRF Connect

I tried it with a Module installed in our PCB, but also with a dev kit. Both have the same behavior. 

I didn't try if two lyra modules could see each other. I will do that and also use another phone.

**Comment by JoLo33** [comment] 2023-04-28 07:32
Hi, so we tested it now also with another phone.

Galaxy A51
Android 13

, a Windows 10 computer and a other LyraP Dev Kit with the newest Firmware. All can find the module if the ATS 100=9 but if I change to ATS 100=121 it can't be found. 

We played around with the ATS 100 setting again. Here is the description:

100 Start-up Flags
▪ Bit 0: Set to VSP Connectable - hence populates GATT table and starts
adverts
▪ Bit 1: Ignored if bit 0 is 1; otherwise start advertising with no timeout
▪ Bit 2: Ignored if bit 0 is 1; otherwise start scanning with no timeout
▪ Bit 3: Set for max bidirectional throughput of about 127kbps, otherwise
half of that.
▪ Bit 4: Use Data Length Extension
▪ Bits 5:6: PHY Rate
 00 – 1MPHY
 01 – Long Range – 125kbps
 10 – RFU : will set 1 MPHY
 11 – 2MPHY
▪ Bit 7: Reserved for Future Use (RFU)

Default is 9 -> VSP and Max throughput enabled -> Working with phone to Lyra
25 -> VSP, Max throughput, DLE  -> Working with phone to Lyra
105 -> VSP, Max throughput, 2MPHY enabled  -> Working with phone to Lyra
121 -> VSP, Max throughput, DLE, 2MPHY enabled  -> NOT Working with phone to Lyra

Best Jonas

**Comment by FlorianBaumgartl-Ezurio** [comment] 2023-06-07 10:35
Hi, Jonas. I just want to quickly inform you that we were able to find, isolate and fix the root cause for this issue based on your error description. The appropriate modifications will be part of the next GA release. Thanks again for all the great information you reported and shared with us here.

Based on further investigations there was a change between GA1.2 and GA2 in regard to how PHY settings are handled in the AT Interface app due to the different Bluetooth stack versions used. In this case, Bit 5 (PHY Rate) of ATS 100 (Start-up Flag) was causing the Lyra module to completely disappear from BLE scanning.

Thanks,
Florian.

**Comment by FlorianBaumgartl-Ezurio** [comment] 2023-06-07 10:36
This is for future reference and documentation purposes only. Bug ID **24822** has been assigned to this issue.

**Comment by FlorianBaumgartl-Ezurio** [comment] 2023-09-12 12:18
This issue has been resolved in the Lyra GA2.2 release (https://github.com/LairdCP/Lyra_Firmware/releases/tag/GA2.2).

**Closed as completed by FlorianBaumgartl-Ezurio** 2023-09-12 12:18 UTC
Labels: bug, software
